name: "test cicd"

on:
 push:
  tags:
   - "*"

jobs:
 dev:
  runs-on: ubuntu-latest
  steps:
   - name: print me
     run: echo "hello, iam working on tag push"
   - name: checkout to version
     uses: actions/checkout@v4
   - name: generate version from package.json
     run: |
      VERSION=$(node -p "require('./package.json').version")
      echo "DEV_VERSION=${VERSION}" >> $GITHUB_ENV

 build:
  needs: dev
  runs-on: ubuntu-latest
  steps: 
   - name: print version generated in dev
     run: echo "${{ env.DEV_VERSION }}"
